# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'e:\code\Python\amlogic_debug_tool\aml_debug_help_info.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AmlDebugHelpAboutInfo_Dialog(object):
    def setupUi(self, AmlDebugHelpAboutInfo_Dialog):
        AmlDebugHelpAboutInfo_Dialog.setObjectName("AmlDebugHelpAboutInfo_Dialog")
        AmlDebugHelpAboutInfo_Dialog.resize(358, 209)
        self.pushButton = QtWidgets.QPushButton(AmlDebugHelpAboutInfo_Dialog)
        self.pushButton.setGeometry(QtCore.QRect(110, 170, 93, 28))
        self.pushButton.setObjectName("pushButton")
        self.AmlDebugHelpAboutInfo_Label = QtWidgets.QLabel(AmlDebugHelpAboutInfo_Dialog)
        self.AmlDebugHelpAboutInfo_Label.setGeometry(QtCore.QRect(30, 10, 301, 151))
        self.AmlDebugHelpAboutInfo_Label.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.AmlDebugHelpAboutInfo_Label.setObjectName("AmlDebugHelpAboutInfo_Label")

        self.retranslateUi(AmlDebugHelpAboutInfo_Dialog)
        self.pushButton.clicked.connect(AmlDebugHelpAboutInfo_Dialog.accept)
        QtCore.QMetaObject.connectSlotsByName(AmlDebugHelpAboutInfo_Dialog)

    def retranslateUi(self, AmlDebugHelpAboutInfo_Dialog):
        _translate = QtCore.QCoreApplication.translate
        AmlDebugHelpAboutInfo_Dialog.setWindowTitle(_translate("AmlDebugHelpAboutInfo_Dialog", "Amlogic Debug Tool"))
        self.pushButton.setText(_translate("AmlDebugHelpAboutInfo_Dialog", "Ok"))
        self.AmlDebugHelpAboutInfo_Label.setText(_translate("AmlDebugHelpAboutInfo_Dialog", "<html><head/><body><p><br/></p></body></html>"))
