# Do not modify this file, it's automatically generated by the compile.py
class AmlDebugConstant():
    AML_DEBUG_TOOL_ABOUT_VERSION            = '1.2.8'
    AML_DEBUG_TOOL_ABOUT_USERE              = 'hongchao.yin'
    AML_DEBUG_TOOL_ABOUT_DATE               = '2021-10-22 17:01:22'
    AML_DEBUG_TOOL_ABOUT_COMMIT             = '693b5f2 (not included this time)'
