# Do not modify this file, it's automatically generated by the compile.py
class AmlDebugConstant():
    AML_DEBUG_TOOL_ABOUT_VERSION            = '1.4.1'
    AML_DEBUG_TOOL_ABOUT_USERE              = 'hongchao.yin'
    AML_DEBUG_TOOL_ABOUT_DATE               = '2022-03-07 17:04:17'
    AML_DEBUG_TOOL_ABOUT_COMMIT             = 'b0e212f (not included this time)'
    AML_DEBUG_TOOL_COMPILE_EXE_TYPE_EXECUTABLE   = 'executable'
    AML_DEBUG_TOOL_COMPILE_EXE_TYPE_INSTALLER    = 'installer'
    AML_DEBUG_TOOL_COMPILE_EXE_TYPE              = 'installer'
