# Do not modify this file, it's automatically generated by the compile.py
class AmlDebugConstant():
    AML_DEBUG_TOOL_ABOUT_VERSION            = '1.2.0'
    AML_DEBUG_TOOL_ABOUT_USERE              = 'hongchao.yin'
    AML_DEBUG_TOOL_ABOUT_DATE               = '2021-09-02 14:16:41'
    AML_DEBUG_TOOL_ABOUT_COMMIT             = '44f06b2 (not included this time)'
